### ISSUE TITLE
albumart doesnt show

### ISSUE THREAD

**Issue by eoli3n** [eworm-de/mpd-notification#12]
My music is in /home/music, and not in /home/$USER/music

I configured XDG_MUSIC_DIR in ~/.config/user-dirs.dirs
XDG_MUSIC_DIR="/home/music"

Also configure systemd user service just to be sure
ExecStart=/usr/bin/mpd-notification -t 5 -m /home/music

I tried to rename my albumart.jpg and png to folder.jpg or folder.png.
It shows a little lamp where the cover needs to be print. (which not appear without setting music folder).

I can't start mpd-notification alone, it freeze.
It only work with systemd service. So i edited it to add -v option
It print me some errors -> 

    sept. 19 22:56:31 osz mpd-notification[14318]: /usr/bin/mpd-notification: Error "GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.66 was not provided by  .service files" while trying to show notification. Trying to reconnect.
    sept. 19 23:03:51 osz mpd-notification[14318]: /usr/bin/mpd-notification: Error "GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.99 was not provided by  .service files" while trying to show notification. Trying to reconnect.

    sept. 19 23:05:20 osz mpd-notification[14318]: (process:14318): GLib-GObject-WARNING **: gsignal.c:2635: instance '0x5597ee645900' has no handler with id '7'

**Comment by eworm-de** [comment]
Looks like anything is wrong with your `dbus` setup. With these error messages I would expect `mpd-notification` to not show any notifications at all.

When started in verbose mode (with `-v` parameter) your first log entry should looks something like this:
```
/usr/bin/mpd-notification: mpd-notification v0.7.4 (compiled: May 10 2016, 15:35:24)
```

**Comment by eoli3n** [comment]
When starting with -v
     mpd-notification -v
     mpd-notification: mpd-notification v0.7.4 (compiled: Sep 19 2016, 23:06:24)

I use systemd 231-1, dbus is default enabled with systemd.

    systemctl --all | grep dbus
    dbus.service                    loaded    active   running   D-Bus System Message Bus
    dbus.socket                     loaded    active   running   D-Bus System Message Bus Socket

I will try to debug that and will tell you more later.

**Comment by eoli3n** [comment]
ah... it works now, i don't have errors anymore with -v in service file, without doing anything...

    mpd-notification

still not work, but i use the service without problems.

Icon problem comes from my notification daemon "dunst". It dont print jpeg, it works with png files.
