### ISSUE TITLE
Can't get cover art

### ISSUE THREAD

**Issue by chowbok** [eworm-de/mpd-notification#16]
I have MPD running on another server, with the audio directory mounted to my local machine via NFS. Notifications are working fine but it can't seem to get cover art. I have "music-dir" set to the NFS-mounted audio file in my config. Not sure how to get it to tell me where it's looking or how it's failing.

**Comment by eworm-de** [comment]
You should start `mpd-notification` with the `-v` switch. It should print more information:
```
mpd-notification: mpd-notification v0.8.1 (compiled: Jan  5 2017, 16:36:14)
mpd-notification: MIME type for /srv/media/music//albums/Roxette/Look_Sharp/08_Dangerous.ogg is: audio/ogg
mpd-notification: Found image file: folder.jpg
[...]
```

**Comment by chowbok** [comment]
I tried that, it's not really telling me much:
`octopus: /home/kjs/.config> mpd-notification  -v
mpd-notification: mpd-notification v0.8.1 (compiled: Mar  2 2017, 11:26:06)
mpd-notification: Playing <b>Jesus Will Make It All Right</b>
by <i>Rev. Edward W. Clayborn</i>
from <i>Rev. Edward W. Clayton: Complete Recordings (1926–1928)</i>
mpd-notification: Playing <b>Bye and Bye When the Morning Comes</b>
by <i>Rev. Edward W. Clayborn</i>
from <i>Rev. Edward W. Clayton: Complete Recordings (1926–1928)</i>
mpd-notification: Playing <b>Jesus Will Make It All Right</b>
by <i>Rev. Edward W. Clayborn</i>
from <i>Rev. Edward W. Clayton: Complete Recordings (1926–1928)</i>
mpd-notification: Stopped playback
mpd-notification: Playing <b>Touchdown</b>
by <i>The Blossoms</i>
from <i>Shockwave</i>
mpd-notification: Playing <b>Touchdown</b>
by <i>The Blossoms</i>
from <i>Shockwave</i>
mpd-notification: Stopped playback
`

**Comment by eworm-de** [comment]
Ok, let's go step by step. Is it compiled with `libav`? Run (on the system you compiled):
```
pkg-config --cflags --libs libavformat libavutil
```
BTW, what system is this?

**Comment by eworm-de** [comment]
Or build 44d32dd9b71d276f95d10978170d0ee5525ed694, `mpd-notification -V` should list `+libav`.

**Comment by chowbok** [comment]
```
octopus: /home/kjs> pkg-config --cflags --libs libavformat libavutil
-lavformat -lavutil
```
This is Arch Linux.

**Comment by chowbok** [comment]
Not sure if this helps, but just in case:
`octopus: /home/kjs> ldd /usr/bin/mpd-notification |grep libav`
	`libavformat.so.57 => /usr/lib/libavformat.so.57 (0x00007f2e29b99000)`
	`libavutil.so.55 => /usr/lib/libavutil.so.55 (0x00007f2e29919000)`
	`libavcodec.so.57 => /usr/lib/libavcodec.so.57 (0x00007f2e25c0c000)`

**Comment by eworm-de** [comment]
That looks good.

And the cause is something completely different. Cover lookup is disabled when connected to remote hosts... Probably it works if you comment or remove lines `332` and `333` from `mpd-notification.c`.

Looks like I have to reconsider.

**Comment by chowbok** [comment]
That fixed it, thanks!

I have a couple more issues. Should I just put them in the comments here, or open new bug reports?

**Comment by eworm-de** [comment]
Please open separate issues.
