### ISSUE TITLE
TIMEOUT only works from command line

### ISSUE THREAD

**Issue by chowbok** [eworm-de/mpd-notification#18]
I tried setting the TIMEOUT to various values in my config, but it doesn't change. Setting it via -t works, however. I know it's reading my config because it's connecting to the correct server, etc.

**Comment by eworm-de** [comment]
The timeout from configuration file is read on line 255. I do not see a reason why this should fail... Make sure not to give extra `-t` on the command line, that overwrites the value from configuration file.

**Comment by eworm-de** [comment]
Just verified, works for me. Make sure to give just numeric value (in seconds). No precision, no suffix.

**Comment by chowbok** [comment]
Well, I've tested it and tested it, I swear it only works from the command line. Here's my config:
`host = squirrel`
`port = 6600`
`music-dir = /squirrel/audio/`
`timeout = 30`
`scale = 500`
I guess I'll just add the flag in the systemd file for now.

**Comment by eworm-de** [comment]
Ah, found the issue. I tested with small values and did not notice this is not exactly what was expected. In config file values of `ms` (like `timeout = 30000`) would work...

**Comment by eworm-de** [comment]
Make sure to update (or remove) `config.h` for a clean default value.
