### ISSUE TITLE
Feature: Limit size of album art

### ISSUE THREAD

**Issue by lucc** [eworm-de/mpd-notification#2]
Some of my album art files are quiet big (nice in some other programs). But that way the notifications get very big as well (at least in awesome WM, have not tried gnome or others).

Is it possible to scale the images before using them in the notification? 

Maybe a new command line option can be added for this, in order not to change the current default behavior.  The command line option could take an argument to give the maximum number of pixles (any bigger images will then be scaled down on the fly).

**Comment by eworm-de** [comment]
Currently I do handle file pathes only, libnotify is given the path to the artwork image. Adding support for scaling images would make it a lot more complex... I would like to avoid that.

In addition to that my notification daemon [xfce4-notifyd](http://goodies.xfce.org/projects/applications/xfce4-notifyd) does scale on its own, so I do not suffer this problem...
What notification daemon are you using? Does it have settings for image manipulation?

**Comment by lucc** [comment]
I use [awesome WM](http://awesome.naquadah.org/) and it's internal notification system (a lua library called `naugthy`). I did not see any options like this till now. I will have to look a little further,

**Comment by eworm-de** [comment]
Looks like naughty does not have a default value for icon size, but it can be defined:
* [Naughty - awesome](https://awesome.naquadah.org/wiki/Naughty#Setting_up_Naughty)
* [awesome API documentation - module naughty](http://awesome.naquadah.org/doc/api/modules/naughty.html#notify)

**Comment by lucc** [comment]
Thanks, that solved it.
