### ISSUE TITLE
scale configuration has no impact

### ISSUE THREAD

**Issue by DamienCassou** [eworm-de/mpd-notification#26]
In mpd-notification.conf, I configured both `music-dir` and `scale`. I can see album pictures in notifications now, but they are very small. I tried to increase the `scale` to 600 (the size of the image in the music file metadata) but this has no impact (I restarted the systemd service in between).

**Comment by eworm-de** [comment]
What notification daemon do you use? Usually that gives the maximum icon size to display. Often its is just 48x48 pixels. Everything larger than that is scaled down automatically.

In fact that functionality is a workaround for notifications daemons that do *not* scale down but tend to show really huge notifications on half of the screen, see #2 where awesome's notification daemon naughty has this problem.

**Comment by DamienCassou** [comment]
I had a look a look at dunst's configuration and you are right: there was a configuration parameter there too. Sorry for the noise.
