### ISSUE TITLE
music-dir not required anymore

### ISSUE THREAD

**Issue by Dankr4d** [eworm-de/mpd-notification#27]
The music-dir configuration option for reading the album art out of files isn't required anymore since mpd added the albumart to there protocol (https://github.com/MusicPlayerDaemon/MPD/pull/86).
Documentation can also be found here: https://www.musicpd.org/doc/html/protocol.html#the-music-database

**Comment by eworm-de** [comment]
But `mpd` can read image data from plain image file `cover.{png,jpg,tiff,bmp}` only, no? Not we can read embedded data from media files... So I would prefer to keep our feature. Or did I miss any details?

**Comment by Dankr4d** [comment]
I opened this issue quite to early. I've seen now, that this feature only supports loading files with the filename “cover” with any of “.png, .jpg, .tiff, .bmp” extensions. That's realy bad.
I think this issue could be closed. Sorry ;)

**Comment by eworm-de** [comment]
Thanks anyway. Please open another issue if mpd supports what we need.

**Comment by Nemo157** [comment]
Since 0.22 MPD now supports reading embedded images too: <https://www.musicpd.org/doc/html/protocol.html#command-readpicture>

**Comment by eworm-de** [comment]
Ah, nice... Still `libmpdclient` does not (yet?) support this, no? Will have to take a detailed look.

**Comment by Nemo157** [comment]
Correct, it sounds like there is an implementation for it that will hopefully be PRed soon <https://github.com/MusicPlayerDaemon/libmpdclient/issues/21>.

**Comment by eworm-de** [comment]
Subscribed... Thanks for the link.
