### ISSUE TITLE
Can this work on a tty with gnome open (or not) on another tty?

### ISSUE THREAD

**Issue by i30817** [eworm-de/mpd-notification#32]
A bit of context: I'm interested in controlling mpd with media keys on a tty, and tried out mpris2 https://github.com/eonpatapon/mpDris2

There i was informed that what i wanted isn't possible for them, since they depend on the gnome-settings-daemon daemon being running to get the keys.

I was also further reminded that there is a rule somewhere about 'only one notification daemon can be registered on dbus at a time', which definitely sinks any further attempts when both gnome and ncmpcpp are running on different ttys but the same user i believe. I'm uncertain if systemd units can coordinate a eventual 'TTY media keys daemon' so it's not running at the same time as gnome, or if there is a much better way listening to edev directly.

This issue is just a query 'is this going to stay impossible on the foreseeable future'?

Eh. A modern shell tty running alacritty and 3d acceleration and a notification daemon would be quite interesting. I hope to see something like that eventually.

**Comment by eworm-de** [comment]
No idea, I guess this is out of scope. This program just links against `libnotify` and uses it to send notifications. You can do what ever `libnotify` supports.
