### ISSUE TITLE
starting playback

### ISSUE THREAD

**Issue by yuceltoluyag** [eworm-de/mpd-notification#33]
` 5.3.13-arch1-1 #1 SMP PREEMPT Sun, 24 Nov 2019 10:15:50 +0000 x86_64 GNU/Linux`
Music Player Daemon 0.21.16 (0.21.16)

```
systemctl --user status mpd-notification
● mpd-notification.service - MPD Notification
   Loaded: loaded (/usr/lib/systemd/user/mpd-notification.service; enabled; ven>
   Active: active (running) since Fri 2019-11-29 19:20:28 +03; 1s ago
 Main PID: 22054 (mpd-notificatio)
   Status: "Waiting for mpd event..."
   CGroup: /user.slice/user-1000.slice/user@1000.service/mpd-notification.servi>
           └─22054 /usr/bin/mpd-notification

```

![mpd](https://i.ibb.co/XLjcp3v/pic-selected-191129-1909-33.png)

**Comment by yuceltoluyag** [comment]
https://github.com/maxice8/mpd-notification solved  @maxice8 repo

**Comment by eworm-de** [comment]
Still no idea about the issue...
... and no idea how that repository may have fixed anything.

**Comment by maxice8** [comment]
It is not, my repo fork is for another PR that adds support for
XDG_CONFIG_HOME.

I don't have any clue why he mentioned it as well

**Comment by yuceltoluyag** [comment]
hi, maybe it was due to the previous kernel version.I don't know exactly what the problem is I installed the aur version again and it worked https://aur.archlinux.org/packages/mpd-notification/  I don't understand why something like this happened  @eworm-de  @maxice8

**Comment by yuceltoluyag** [comment]
again problem

uname -a
Linux jasonV 5.5.7-arch1

```
systemctl status --user mpd-notification.service 
● mpd-notification.service - MPD Notification
     Loaded: loaded (/usr/lib/systemd/user/mpd-notification.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2020-03-05 12:55:25 +03; 5min ago
    Process: 679 ExecStart=/usr/bin/mpd-notification (code=exited, status=1/FAILURE)
   Main PID: 679 (code=exited, status=1/FAILURE)
     Status: "Stopped. Bye!"

Mar 05 12:55:25 jasonV systemd[673]: Starting MPD Notification...
Mar 05 12:55:25 jasonV mpd-notification[679]: /usr/bin/mpd-notification: Connection refused
Mar 05 12:55:25 jasonV systemd[673]: mpd-notification.service: Main process exited, code=exited, status=1/FAILURE
Mar 05 12:55:25 jasonV systemd[673]: mpd-notification.service: Failed with result 'exit-code'.
Mar 05 12:55:25 jasonV systemd[673]: Failed to start MPD Notification.
```

I restart it keeps falling the same error  @maxice8  @eworm-de

**Comment by eworm-de** [comment]
Make sure that `mpd` and `dbus` are started.

systemctl is-active mpd.service
systemctl --user is-active mpd.service dbus.service

This should give `active` twice.

**Comment by yuceltoluyag** [comment]
```
systemctl --user is-active mpd.service dbus.service
active
active
systemctl is-active mpd.service
inactive
```

@eworm-de  What should I do ?

**Comment by eworm-de** [comment]
And that is the output also if the issue occurs? `Connection refused` indicates that a service is not running.

**Comment by yuceltoluyag** [comment]
```
systemctl --user is-active mpd.service dbus.service
active
active

```

some music has no notifications,some music sends 2 notifications  https://ibb.co/nBvM1kb

**Comment by yuceltoluyag** [comment]
the last question, is how do you download your music?
I'm downloading from youtube using youtube-dl
`youtube-dl --download-archive downloaded.txt --no-post-overwrites -ciwx --embed-thumbnail --audio-quality 0  --audio-format mp3 -o "%(title)s.%(ext)s`

it automatically creates cover images in mp3 files that i download in this way  for example https://ibb.co/v4nGMVM

belki sorun bundan kaynaklanıyor
> because some music has no notifications,some music sends 2 notifications https://ibb.co/nBvM1kb

@eworm-de

**Comment by yuceltoluyag** [comment]
ok solved my problem : )  ytdl--add-metada  :)  As I guessed,It is caused by a lack of information in music files.
