### ISSUE TITLE
Notification history problem in KDE

### ISSUE THREAD

**Issue by xiangsheng** [eworm-de/mpd-notification#34]
Due to a [change](https://cgit.kde.org/plasma-workspace.git/commit/?id=1f6050b1740cf800cb031e98fd89bc00ca20c55a) in KDE, it seems that the notification sent by mpd-notification can't be preserved in the notification history.

Is that possible to deal with this problem? I find a related workaround [here](https://bbs.archlinux.org/viewtopic.php?id=252208).

**Comment by eworm-de** [comment]
What a stupid change...

Well, `libnotify`'s [documentation](https://developer.gnome.org/notification-spec/#hints) says this about hints on `desktop-entry`:

> This specifies the name of the desktop filename representing the calling program. This should be the same as the prefix used for the application's .desktop file. An example would be "rhythmbox" from "rhythmbox.desktop". This can be used by the daemon to retrieve the correct icon for the application, for logging purposes, etc. 

We do not have a desktop file, so does not make sense to specify this.

What else makes a notification "_configurable_" for plasma?

**Comment by xiangsheng** [comment]
As I understand, if I create a .desktop file locally for the mpd-notification (or just for mpd), it seems possible to make the history work if the code related to sending notification is suitably modified. Am I right?

**Comment by eworm-de** [comment]
I guess yes.

**Comment by xiangsheng** [comment]
So, would you like to add this feature?

**Comment by eworm-de** [comment]
No. That's a dirty hack at best.

If you find documentation how to achieve this without shipping a useless desktop file (or other ugly workaround) I will happily implement it.
