### ISSUE TITLE
Consider adding a --version command line option.

### ISSUE THREAD

**Issue by lucc** [eworm-de/mpd-notification#4]
I just wanted to see which version I have installed (and not start a new instance). But --help only shows the version if I also put -v on the cammand line. I consider this not obvious (and only found out about it after reading the source).

The problem is that the normal greeting might have to be moved to another location in main() for this to be pratical (otherwise --version --verbose might print the same info twice which is not really verbose but redundant).

**Comment by eworm-de** [comment]
Implemented with 02a7441b621db03161061dbfd5a93f1a1adc7e75.
