### ISSUE TITLE
Show mode change notifications

### ISSUE THREAD

**Issue by tristengrant** [eworm-de/mpd-notification#44]
Is there a way to show mode change notifications? I'm using NCMPCPP and would like a notification of when I change shuffle and repeate modes. Is this something mpd-notification can show?

**Comment by eworm-de** [comment]
Currently no, and I have no idea if it *would* be possible. I would have to look at the API.

But what is the rational here? When you change the mode you should know, no?

**Comment by tristengrant** [comment]
Mainly so that I know it went through and to remember if its on or off. Although I figured out a way using dunst and mpc.
