### ISSUE TITLE
Cover art not working

### ISSUE THREAD

**Issue by Fxzzi** [eworm-de/mpd-notification#45]
music-dir has been set correctly and mpd-notification can correctly find my music files:

```
~ $ mpd-notification -v                                        
mpd-notification: mpd-notification v0.8.7 +systemd +libav (compiled: May 19 2024, 18:36:54)
mpd-notification: MIME type for /home/faaris/Music//Sullivan King/Someone Else/01 Someone Else.m4a is: audio/x-m4a
mpd-notification: Playing <b>Someone Else</b> by <i>Sullivan King</i> from <i>Someone Else</i>
```

Is this due to my music being in the m4a format? I am using dunst, and I have also attempted to use the notification-file to no avail, it just shows a generic music file icon.

**Comment by eworm-de** [comment]
Probably, yes. Does it work if you comment these two lines?
https://github.com/eworm-de/mpd-notification/blob/e167b84f164904fcc14498a27026b5a354a5d0ad/mpd-notification.c#L108

**Comment by eworm-de** [comment]
Can you please test with d692afcff131e6bd5f9ab8ba5bcdf825b8329228 (or `artwork` branch)?

**Comment by eworm-de** [comment]
Ping... Any chance you test this?

**Comment by eworm-de** [comment]
Formatting options are a different topic, please open a separate issue for that.
