### ISSUE TITLE
GLib critical message on g_markup_escape_text: assertion

### ISSUE THREAD

**Issue by Narrat** [eworm-de/mpd-notification#5]
Dunno if this a real problem, but if Critical is displayed I want to be sure. Though, I didn't notice a problem. Just a message on stdout.

Listening to a radio stream and the following error is produced:
>(process:32163): GLib-CRITICAL **: g_markup_escape_text: assertion 'text != NULL' failed

and the notify looks like that
![1436403240](https://cloud.githubusercontent.com/assets/2787518/8585727/77a0f18a-25e6-11e5-8415-0e074049eabd.png)

**Comment by eworm-de** [comment]
Should be fixed with 53950b19fc05087cc90aef36ddc391d4c28eb169. Can you verify, please?

**Comment by Narrat** [comment]
Yes, the error message is gone and the empty by/from won't be displayed
