### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by diskotechjam** [eworm-de/mpd-notification#9]
I want to change the message format to better fit my desktop theme. Where is the config file located?

**Comment by eworm-de** [comment]
There is no traditional config file you can change at runtime.

However you can run `make config`, edit `config.h` (see `TEXT_*` definitions) and compile with `make`.

What would you like it to look like?

**Comment by diskotechjam** [comment]
I wanted to eliminate the line breaks and have a single line of text to cover the panel at the top of my screen. I was able to acheive this using the dunst "ignore new line"  config, so everything looks good now. Thanks for the info.
